# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 808d03d72ee8c0c591f8c033dd484d8c70d3535aac1eca0109fdbc34c21a5ccb79a306dfa286cc8a99785beb2bb56057b5890f217a6c8e36d006e588d017d098

test:
  secret_key_base: fd1f9f7784ea6e7140fc1e2a075707a63548ecb026c5495171ab627a16b3be7852ddea276718e80b551136c75b10ff8b5034aea341d462b0920457c9cd5ffa04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
